const state={api:localStorage.getItem('tar_api')||'http://localhost:8000',apiKey:sessionStorage.getItem('tar_api_key')||'',adminKey:sessionStorage.getItem('tar_admin_key')||'',lastJob:null};
const $=id=>document.getElementById(id);const headers=(admin=false,json=true)=>{const h={};if(json)h['Content-Type']='application/json';if(state.apiKey)h['X-TAR-API-Key']=state.apiKey;if(admin&&state.adminKey)h['X-TAR-Admin-Key']=state.adminKey;return h};
async function request(path,opts={}){const r=await fetch(state.api+path,opts);let body;const ct=r.headers.get('content-type')||'';body=ct.includes('application/json')?await r.json():await r.text();if(!r.ok)throw new Error(typeof body==='string'?body:(body.detail||JSON.stringify(body)));return body}
function safe(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function showJSON(id,data){$(id).textContent=JSON.stringify(data,null,2)}
function renderList(id,items,renderer){$(id).innerHTML=(items||[]).map(renderer).join('')||'<div class="small">No records.</div>'}
function activate(name){document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',x.dataset.panel===name));document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x.dataset.tab===name))}
async function health(){try{const d=await request('/health');$('health').textContent=`API ${d.version} online`;$('health').className='badge ok';$('memoryCount').textContent=d.memory?.records??'—';$('govState').textContent=d.governance?.configured?(d.governance.connected?'connected':'configured/offline'):'not configured'}catch(e){$('health').textContent='API offline';$('health').className='badge'}}
async function ask(){const q=$('askQuery').value.trim();if(!q)return;$('askOutput').textContent='Researching…';$('askSources').innerHTML='';try{const d=await request('/v1/ask',{method:'POST',headers:headers(),body:JSON.stringify({query:q,research:$('askResearch').checked})});$('askOutput').textContent=d.answer||'';renderList('askSources',d.sources,s=>`<div class="item"><div><b>${safe(s.title||'Untitled')}</b></div><div class="meta">${safe(s.source||'record')} ${s.page?'• page '+safe(s.page):''} ${s.url?`• <a target="_blank" rel="noopener" href="${safe(s.url)}">source</a>`:''}</div><div class="source-snippet">${safe((s.snippet||'').slice(0,900))}</div></div>`)}catch(e){$('askOutput').textContent=e.message}}
async function recall(){try{const d=await request('/v1/memory/recall',{method:'POST',headers:headers(),body:JSON.stringify({query:$('recallQuery').value,limit:20,source:$('recallSource').value||null})});renderList('recallResults',d.results,s=>`<div class="item"><b>${safe(s.title||s.kind||'Record')}</b><div class="meta">${safe(s.source||'')} ${s.page?'• page '+safe(s.page):''} • score ${safe(s.retrieval_score??s.memory_score??'')}</div><div class="source-snippet">${safe((s.snippet||'').slice(0,1200))}</div></div>`)}catch(e){$('recallResults').textContent=e.message}}
async function ingest(){const f=$('ingestFile').files[0];if(!f)return showJSON('ingestStatus',{error:'Choose a file'});const fd=new FormData();fd.append('file',f);if($('ingestTitle').value)fd.append('title',$('ingestTitle').value);fd.append('source',$('ingestSource').value||'upload');if($('ingestUri').value)fd.append('source_uri',$('ingestUri').value);const h={};if(state.apiKey)h['X-TAR-API-Key']=state.apiKey;try{const d=await request('/v1/ingest/file',{method:'POST',headers:h,body:fd});showJSON('ingestStatus',d);loadDocuments()}catch(e){showJSON('ingestStatus',{error:e.message})}}
async function loadDocuments(){try{const d=await request('/v1/documents?limit=100',{headers:headers(false,false)});renderList('documentsList',d.documents,x=>`<div class="item"><b>${safe(x.title)}</b><div class="meta">${safe(x.source)} • ${safe(x.media_type)} • ${safe(x.document_id)}</div></div>`)}catch(e){$('documentsList').textContent=e.message}}
async function queueJob(){try{const d=await request('/v1/jobs',{method:'POST',headers:headers(),body:JSON.stringify({kind:$('jobKind').value,prompt:$('jobPrompt').value,options:{}})});state.lastJob=d.job_id;$('jobId').value=d.job_id;showJSON('jobStatus',d)}catch(e){showJSON('jobStatus',{error:e.message})}}
async function pollJob(){const id=$('jobId').value||state.lastJob;if(!id)return;try{const d=await request('/v1/jobs/'+encodeURIComponent(id),{headers:headers(false,false)});showJSON('jobStatus',d);if(['queued','running'].includes(d.status))setTimeout(()=>pollJob(),2500)}catch(e){showJSON('jobStatus',{error:e.message})}}
async function loadArtifacts(){try{const d=await request('/v1/artifacts?limit=100',{headers:headers(false,false)});renderList('artifactsList',d.artifacts,x=>`<div class="item"><b>${safe(x.name)}</b><div class="meta">${safe(x.media_type)} • ${safe(x.size_bytes)} bytes • ${safe(x.sha256)}</div><button class="secondary" onclick="downloadArtifact('${safe(x.artifact_id)}','${safe(x.name)}')">Download</button></div>`)}catch(e){$('artifactsList').textContent=e.message}}
async function downloadArtifact(id,name){const r=await fetch(state.api+'/v1/artifacts/'+id,{headers:headers(false,false)});if(!r.ok)return alert('Download failed');const b=await r.blob(),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name||id;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
async function loadNodes(){try{const d=await request('/v1/nodes',{headers:headers(false,false)});renderList('nodesList',d.nodes,n=>`<div class="item"><b>${safe(n.name)}</b><div class="meta">${safe(n.node_id)} • reputation ${safe(n.reputation)} • ${n.active?'active':'inactive'}</div><div>${safe((n.capabilities||[]).join(', '))}</div></div>`)}catch(e){$('nodesList').textContent=e.message}}
async function loadGovernance(){try{showJSON('governanceStatus',await request('/v1/governance',{headers:headers(false,false)}))}catch(e){showJSON('governanceStatus',{error:e.message})}}
async function loadAudit(){try{const d=await request('/v1/audit?limit=100',{headers:headers(false,false)});renderList('auditList',d.events,e=>`<div class="item"><b>${safe(e.action)}</b><div class="meta">${safe(e.actor)} • ${safe(e.object_type)} ${safe(e.object_id)} • ${safe(e.created_at)}</div><div class="small">${safe(e.event_hash)}</div></div>`)}catch(e){$('auditList').textContent=e.message}}
async function verifyAudit(){try{showJSON('auditVerify',await request('/v1/audit/verify',{headers:headers(false,false)}))}catch(e){showJSON('auditVerify',{error:e.message})}}
async function createWorkspace(){try{showJSON('adminOutput',await request('/v1/admin/workspaces',{method:'POST',headers:headers(true),body:JSON.stringify({name:$('workspaceName').value,owner:$('workspaceOwner').value||'local'})}))}catch(e){showJSON('adminOutput',{error:e.message})}}
async function createKey(){try{const d=await request('/v1/admin/api-keys',{method:'POST',headers:headers(true),body:JSON.stringify({label:$('keyLabel').value,workspace_id:$('keyWorkspace').value||'default'})});showJSON('adminOutput',d)}catch(e){showJSON('adminOutput',{error:e.message})}}
function saveSettings(){state.api=$('apiBase').value.replace(/\/$/,'');state.apiKey=$('apiKey').value;state.adminKey=$('adminKey').value;localStorage.setItem('tar_api',state.api);sessionStorage.setItem('tar_api_key',state.apiKey);sessionStorage.setItem('tar_admin_key',state.adminKey);health()}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{activate(b.dataset.tab);if(b.dataset.tab==='documents')loadDocuments();if(b.dataset.tab==='jobs'&&state.lastJob)pollJob();if(b.dataset.tab==='artifacts')loadArtifacts();if(b.dataset.tab==='nodes')loadNodes();if(b.dataset.tab==='governance')loadGovernance();if(b.dataset.tab==='audit')loadAudit()});
window.ask=ask;window.recall=recall;window.ingest=ingest;window.queueJob=queueJob;window.pollJob=pollJob;window.loadDocuments=loadDocuments;window.loadArtifacts=loadArtifacts;window.downloadArtifact=downloadArtifact;window.loadNodes=loadNodes;window.loadGovernance=loadGovernance;window.loadAudit=loadAudit;window.verifyAudit=verifyAudit;window.createWorkspace=createWorkspace;window.createKey=createKey;window.saveSettings=saveSettings;
window.addEventListener('DOMContentLoaded',()=>{$('apiBase').value=state.api;$('apiKey').value=state.apiKey;$('adminKey').value=state.adminKey;activate('ask');health()});